name: Nerdctl Action
description: Ação personalizada para usar o nerdctl no GitHub Actions

runs:
  using: "docker"
  image: "Dockerfile"

inputs:
  entryPoint:
    description: 'O comando a ser executado'
    required: true

  args:
    description: 'Argumentos para o comando'
    required: false

outputs:
  result:
    description: 'Saída do comando nerdctl'

branding:
  icon: 'cpu'
  color: 'purple'
